---
- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - make
    - vlan
    - libnl-utils
    - gcc
    - cmake
    - libcrypto++-dev
    - libcrypto++9
    - libcrypto++-utils
    - lua5.1
    - liblua5.1-0-dev
    - libpcre++-dev
    - libpcre++0
    - libpcre3
    - libpcrecpp0
    - libsnmp-dev
    - iftop
    - iptraf
    - ipset
    - libipset-dev

