---
#  - name: nat for OS {{ ansible_distribution_major_version }}
#    include: "{{ ansible_distribution_major_version }}.yml"

  - name: linux-headers
    apt: pkg=linux-headers-{{ kernel }} state=present update_cache=true


