---
  - name: copy firewall
    copy:
      src: firewall
      dest: /etc/init.d
      mode: a+x

  - name: update-rc.d firewall
    command: "update-rc.d firewall defaults"

  - name: firewall started
    service:
      name: firewall
      state: started
